function verify = func_EDMD(x, u, y,model_order, EDMD, num_training_sample, model_order_u)
%%
global model;
% %
num_sample = size(u,1);
num_xpre = size(x,1);
num_lift_x = size(model.data.pipeline(9).x, 2);
num_lift_y = size(model.data.pipeline(9).y, 2);

%% training data
k_interval = 1 : num_xpre;

verify.x = sdpvar(num_sample, num_lift_x, 'full');
verify.A11_x = sdpvar(num_sample -  model_order, num_lift_x, model_order, 'full');
verify.A12_y = sdpvar(num_sample -  model_order, num_lift_x, model_order, 'full');
verify.B11_u = sdpvar(num_sample -  model_order, num_lift_x, model_order_u, 'full');

verify.y = sdpvar(num_sample, num_lift_y, 'full');
verify.A21_x = sdpvar(num_sample -  model_order, num_lift_y, model_order, 'full');
verify.A22_y = sdpvar(num_sample -  model_order, num_lift_y, model_order, 'full');
verify.B21_u = sdpvar(num_sample -  model_order, num_lift_y, model_order_u, 'full');
% 
% model.oef.cons = model.oef.cons + ( ...
%     () : ...
%     '');%2*5时刻1和时刻2的状态变量
% model.oef.cons = model.oef.cons + ( ...
%     () : ...
%     '');%2*5时刻1和时刻2的状态变量
verify.x(k_interval, :) = x(k_interval, :);
verify.y(k_interval, :) = y(k_interval, :);

% % x
for k_interval = num_training_sample - model_order + 1 : num_sample - model_order % 6:29
    for k_order = 1 : model_order
         model.oef.cons = model.oef.cons + ( ...
             (verify.A11_x(k_interval, :, k_order) ==  ...
             (EDMD.var.A11(:, :, k_order) * ...
             verify.x(k_interval + model_order - k_order + 1, :)')') : ...
             '');
         model.oef.cons = model.oef.cons + ( ...
             (verify.A12_y(k_interval, :, k_order) ==  ...
             (EDMD.var.A12(:, :, k_order) * ...
             verify.y(k_interval + model_order - k_order + 1, :)')') : ...
             '');
    end

    for k_order = 1 : model_order_u
        model.oef.cons = model.oef.cons + ( ...
            (verify.B11_u(k_interval, :, k_order) ==  ...
            (EDMD.var.B11(:, :, k_order) * ...
            u(k_interval + model_order - k_order + 1, :)')') : ...
            '');
    end
    model.oef.cons = model.oef.cons + ( ...
        (verify.x(k_interval + model_order,:) == ...
        sum(verify.A11_x(k_interval,:,:), 3) + ...
        sum(verify.A12_y(k_interval,:,:), 3) + ...
        sum(verify.B11_u(k_interval,:,:), 3)) : ...
        '');
end
% % y
for k_interval = num_training_sample - model_order + 1 : num_sample - model_order % 6:29
    for k_order = 1 : model_order
         model.oef.cons = model.oef.cons + ( ...
             (verify.A21_x(k_interval, :, k_order) ==  ...
             (EDMD.var.A21(:, :, k_order) * ...
             verify.x(k_interval + model_order - k_order + 1, :)')') : ...
             '');

         model.oef.cons = model.oef.cons + ( ...
             (verify.A22_y(k_interval, :, k_order) ==  ...
             (EDMD.var.A22(:, :, k_order) * ...
             verify.y(k_interval + model_order - k_order + 1, :)')') : ...
             '');
    end
    for k_order = 1 : model_order_u
         model.oef.cons = model.oef.cons + ( ...
             (verify.B21_u(k_interval, :, k_order) ==  ...
             (EDMD.var.B21(:, :, k_order) * ...
             u(k_interval + model_order - k_order + 1, :)')') : ...
             '');
    end
    model.oef.cons = model.oef.cons + ( ...
        (verify.y(k_interval + model_order,:) == ...
        sum(verify.A21_x(k_interval,:,:), 3) + ...
        sum(verify.A22_y(k_interval,:,:), 3) + ...
        sum(verify.B21_u(k_interval,:,:), 3)) : ...
        '');
end



